// GOVAI-PROVENANCE-BEGIN CONT-P5-A (source-derived; regenerate, never hand-edit)
// PIN_RELEASE           = 0.154.0
// PIN_TAG               = rust-v0.154.0
// PIN_COMMIT            = 6b9826e3aa83b1a5947db50f4332cb9c65f1b340
// SOURCE_PATH_OR_SCHEMA = every #[experimental("...")] string annotation under codex-rs/app-server-protocol/src/** (per-entry `anchor` below); classification criterion = the vendored stable TS in ./generated/**
// SOURCE_SHA256         = (per annotated source file)
//   e2f0e4dbee5f0ddcb8c2a47f92df629ee02765c57348cbb4188e950dd1253889  codex-rs/app-server-protocol/src/experimental_api.rs
//   6aa47ec984c9198ea797bf63b784cf6a88cc0ab85efb0a4ac75e01aabffc2cfa  codex-rs/app-server-protocol/src/protocol/common.rs
//   22d4ec67a5979d33cbe2e40b53c7afbdd1bbed935a54b2284e9b2de11f4b590c  codex-rs/app-server-protocol/src/protocol/v2/account.rs
//   e655da7da2984ad6ea198b55829b21db01e05993725dea0f11e9e3de7fb66784  codex-rs/app-server-protocol/src/protocol/v2/command_exec.rs
//   51c06df16539283e97b6b472753f09d16712f9f1e682751ad6c03b779a0c493e  codex-rs/app-server-protocol/src/protocol/v2/config.rs
//   4cb6190f253d18cafea1451a0b062fef891529757762a4ffe9ff3b0af25d00ff  codex-rs/app-server-protocol/src/protocol/v2/item.rs
//   ae6dde792099d0df8bfc78fcf6d30e596b93f28f6af12f693fa87aeca84212ae  codex-rs/app-server-protocol/src/protocol/v2/mcp.rs
//   11c704b5674ab5092ea6255ff3c8bb06f97567f1ff32d1dc09ad33f66277bb86  codex-rs/app-server-protocol/src/protocol/v2/shared.rs
//   ffc2f432bc7d0dadf9ae10db832035c8b75d7b709462bfed3c83d33ea89c526a  codex-rs/app-server-protocol/src/protocol/v2/thread.rs
//   c569abd0f1e3244a495a67da73a6b20ecd029a1184f8d6fd4c97a29c6fbc3ff4  codex-rs/app-server-protocol/src/protocol/v2/thread_data.rs
//   49098e1b594835e6376952c35a0b13cfacd1316eb68bd8a46553842534a86bb2  codex-rs/app-server-protocol/src/protocol/v2/turn.rs
// GENERATOR_IDENTITY    = CONT-P5-A executor derivation (derive_inventory.py + materialize.py, kept with the mission evidence outside the repository; their SHA-256 are recorded in the CONT-P5-A execution report)
// GENERATOR_VERSION     = CONT-P5-A (single derivation at PIN_COMMIT)
// GENERATOR_CONFIG      = category = present-in-vendored-stable-TS ? EXPERIMENTAL_REPRESENTABLE_ON_GENERATED_WIRE : EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE; corroborated against schema/precomputed/app-server-exports-experimental.json.zst
// DERIVATION_MODE       = VERBATIM_SOURCE_DERIVED
// GOVAI-PROVENANCE-END
//
// EXPERIMENTAL_SOURCE_INVENTORY (CONT-P5-A §2 protocol/). Two categories, decided ONLY by comparing each
// annotated item with the vendored generated (experimentalApi = false) TypeScript:
//   (1) EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE       annotated upstream AND absent from ./generated/**
//   (2) EXPERIMENTAL_REPRESENTABLE_ON_GENERATED_WIRE  annotated upstream AND present in ./generated/**
// "Upstream experimental" and "GovAI forbidden" are different axes: values GovAI forbids WITHOUT an upstream
// annotation (category 3) are NOT in this list — see ./govai-policy.ts.
// `experimental-inventory.test.ts` re-derives every category from ./generated/** so this table cannot drift.

export type CodexExperimentalCategory =
  | 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE'
  | 'EXPERIMENTAL_REPRESENTABLE_ON_GENERATED_WIRE';

export interface CodexExperimentalInventoryEntry {
  /** The `#[experimental("…")]` reason string, verbatim. */
  readonly reason: string;
  readonly category: CodexExperimentalCategory;
  /** `method` = a union arm; `field` = an object key; `variant` = an enum arm. */
  readonly kind: 'method' | 'field' | 'variant';
  /** `method`: the generated union (`ClientRequest`, `ServerNotification`, …); otherwise the generated type name. */
  readonly container: string;
  /** Exact wire spelling: the method name, the JSON key, or the variant tag value. */
  readonly wire: string;
  /** Discriminator key of an internally-tagged enum variant (`type`, `mode`); `null` otherwise. */
  readonly tag: string | null;
  /** Client-request methods whose params type IS `container` (request-side items); empty for inbound-only items. */
  readonly requestMethods: readonly string[];
  /** Variants only: every client-request params position holding `container` (`field: null` = the params root). */
  readonly positions: readonly { readonly method: string; readonly field: string | null }[];
  /** Commit-addressed source anchor: `<path>#L<line>` at PIN_COMMIT. */
  readonly anchor: string;
  /** The annotation sits inside a `#[cfg(test)]` module: a derive-macro fixture, never an exported protocol type. */
  readonly cfgTestFixture: boolean;
}

export const CODEX_EXPERIMENTAL_INVENTORY: readonly CodexExperimentalInventoryEntry[] = Object.freeze([
  {
    reason: 'enum/unit',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'variant',
    container: 'EnumVariantShapes',
    wire: 'Unit',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/experimental_api.rs#L69',
    cfgTestFixture: true,
  },
  {
    reason: 'enum/tuple',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'variant',
    container: 'EnumVariantShapes',
    wire: 'Tuple',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/experimental_api.rs#L71',
    cfgTestFixture: true,
  },
  {
    reason: 'enum/named',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'variant',
    container: 'EnumVariantShapes',
    wire: 'Named',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/experimental_api.rs#L73',
    cfgTestFixture: true,
  },
  {
    reason: 'field/optionalCollection',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'ExperimentalFieldShape',
    wire: 'optional_collection',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/experimental_api.rs#L104',
    cfgTestFixture: true,
  },
  {
    reason: 'server/diagnostics',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'method',
    container: 'ClientRequest',
    wire: 'server/diagnostics',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L513',
    cfgTestFixture: false,
  },
  {
    reason: 'userVerification/status',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'method',
    container: 'ClientRequest',
    wire: 'userVerification/status',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L521',
    cfgTestFixture: false,
  },
  {
    reason: 'userVerification/enroll',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'method',
    container: 'ClientRequest',
    wire: 'userVerification/enroll',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L528',
    cfgTestFixture: false,
  },
  {
    reason: 'userVerification/delete',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'method',
    container: 'ClientRequest',
    wire: 'userVerification/delete',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L535',
    cfgTestFixture: false,
  },
  {
    reason: 'userVerification/verify',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'method',
    container: 'ClientRequest',
    wire: 'userVerification/verify',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L542',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/increment_elicitation',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'method',
    container: 'ClientRequest',
    wire: 'thread/increment_elicitation',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L585',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/decrement_elicitation',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'method',
    container: 'ClientRequest',
    wire: 'thread/decrement_elicitation',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L595',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/queue/add',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'method',
    container: 'ClientRequest',
    wire: 'thread/queue/add',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L624',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/queue/list',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'method',
    container: 'ClientRequest',
    wire: 'thread/queue/list',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L630',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/queue/update',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'method',
    container: 'ClientRequest',
    wire: 'thread/queue/update',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L636',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/queue/delete',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'method',
    container: 'ClientRequest',
    wire: 'thread/queue/delete',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L642',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/queue/reorder',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'method',
    container: 'ClientRequest',
    wire: 'thread/queue/reorder',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L648',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/queue/start',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'method',
    container: 'ClientRequest',
    wire: 'thread/queue/start',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L654',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/settings/update',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'method',
    container: 'ClientRequest',
    wire: 'thread/settings/update',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L671',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/memoryMode/set',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'method',
    container: 'ClientRequest',
    wire: 'thread/memoryMode/set',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L678',
    cfgTestFixture: false,
  },
  {
    reason: 'memory/reset',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'method',
    container: 'ClientRequest',
    wire: 'memory/reset',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L684',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/backgroundTerminals/clean',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'method',
    container: 'ClientRequest',
    wire: 'thread/backgroundTerminals/clean',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L710',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/backgroundTerminals/list',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'method',
    container: 'ClientRequest',
    wire: 'thread/backgroundTerminals/list',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L716',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/backgroundTerminals/terminate',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'method',
    container: 'ClientRequest',
    wire: 'thread/backgroundTerminals/terminate',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L722',
    cfgTestFixture: false,
  },
  {
    reason: 'project/list',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'method',
    container: 'ClientRequest',
    wire: 'project/list',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L744',
    cfgTestFixture: false,
  },
  {
    reason: 'project/read',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'method',
    container: 'ClientRequest',
    wire: 'project/read',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L750',
    cfgTestFixture: false,
  },
  {
    reason: 'project/create',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'method',
    container: 'ClientRequest',
    wire: 'project/create',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L756',
    cfgTestFixture: false,
  },
  {
    reason: 'project/import',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'method',
    container: 'ClientRequest',
    wire: 'project/import',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L762',
    cfgTestFixture: false,
  },
  {
    reason: 'project/update',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'method',
    container: 'ClientRequest',
    wire: 'project/update',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L768',
    cfgTestFixture: false,
  },
  {
    reason: 'project/move',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'method',
    container: 'ClientRequest',
    wire: 'project/move',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L774',
    cfgTestFixture: false,
  },
  {
    reason: 'project/delete',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'method',
    container: 'ClientRequest',
    wire: 'project/delete',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L780',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/search',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'method',
    container: 'ClientRequest',
    wire: 'thread/search',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L806',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/searchOccurrences',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'method',
    container: 'ClientRequest',
    wire: 'thread/searchOccurrences',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L812',
    cfgTestFixture: false,
  },
  {
    reason: 'plugin/search',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'method',
    container: 'ClientRequest',
    wire: 'plugin/search',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L882',
    cfgTestFixture: false,
  },
  {
    reason: 'turn/settings/update',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'method',
    container: 'ClientRequest',
    wire: 'turn/settings/update',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L1016',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/realtime/start',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'method',
    container: 'ClientRequest',
    wire: 'thread/realtime/start',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L1033',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/realtime/appendAudio',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'method',
    container: 'ClientRequest',
    wire: 'thread/realtime/appendAudio',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L1039',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/realtime/appendText',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'method',
    container: 'ClientRequest',
    wire: 'thread/realtime/appendText',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L1045',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/realtime/appendSpeech',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'method',
    container: 'ClientRequest',
    wire: 'thread/realtime/appendSpeech',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L1051',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/realtime/stop',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'method',
    container: 'ClientRequest',
    wire: 'thread/realtime/stop',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L1057',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/timeline/list',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'method',
    container: 'ClientRequest',
    wire: 'thread/timeline/list',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L1063',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/realtime/listVoices',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'method',
    container: 'ClientRequest',
    wire: 'thread/realtime/listVoices',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L1069',
    cfgTestFixture: false,
  },
  {
    reason: 'remoteControl/enable',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'method',
    container: 'ClientRequest',
    wire: 'remoteControl/enable',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L1106',
    cfgTestFixture: false,
  },
  {
    reason: 'remoteControl/disable',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'method',
    container: 'ClientRequest',
    wire: 'remoteControl/disable',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L1112',
    cfgTestFixture: false,
  },
  {
    reason: 'remoteControl/status/read',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'method',
    container: 'ClientRequest',
    wire: 'remoteControl/status/read',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L1118',
    cfgTestFixture: false,
  },
  {
    reason: 'remoteControl/pairing/start',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'method',
    container: 'ClientRequest',
    wire: 'remoteControl/pairing/start',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L1124',
    cfgTestFixture: false,
  },
  {
    reason: 'remoteControl/pairing/status',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'method',
    container: 'ClientRequest',
    wire: 'remoteControl/pairing/status',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L1130',
    cfgTestFixture: false,
  },
  {
    reason: 'remoteControl/client/list',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'method',
    container: 'ClientRequest',
    wire: 'remoteControl/client/list',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L1136',
    cfgTestFixture: false,
  },
  {
    reason: 'remoteControl/client/revoke',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'method',
    container: 'ClientRequest',
    wire: 'remoteControl/client/revoke',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L1142',
    cfgTestFixture: false,
  },
  {
    reason: 'collaborationMode/list',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'method',
    container: 'ClientRequest',
    wire: 'collaborationMode/list',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L1148',
    cfgTestFixture: false,
  },
  {
    reason: 'mock/experimentalMethod',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'method',
    container: 'ClientRequest',
    wire: 'mock/experimentalMethod',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L1155',
    cfgTestFixture: false,
  },
  {
    reason: 'environment/add',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'method',
    container: 'ClientRequest',
    wire: 'environment/add',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L1162',
    cfgTestFixture: false,
  },
  {
    reason: 'environment/info',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'method',
    container: 'ClientRequest',
    wire: 'environment/info',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L1169',
    cfgTestFixture: false,
  },
  {
    reason: 'environment/status',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'method',
    container: 'ClientRequest',
    wire: 'environment/status',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L1176',
    cfgTestFixture: false,
  },
  {
    reason: 'mcpServer/event/stream/start',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'method',
    container: 'ClientRequest',
    wire: 'mcpServer/event/stream/start',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L1208',
    cfgTestFixture: false,
  },
  {
    reason: 'mcpServer/event/stream/stop',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'method',
    container: 'ClientRequest',
    wire: 'mcpServer/event/stream/stop',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L1215',
    cfgTestFixture: false,
  },
  {
    reason: 'account/bedrock/discover',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'method',
    container: 'ClientRequest',
    wire: 'account/bedrock/discover',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L1246',
    cfgTestFixture: false,
  },
  {
    reason: 'account/bedrock/setup',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'method',
    container: 'ClientRequest',
    wire: 'account/bedrock/setup',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L1253',
    cfgTestFixture: false,
  },
  {
    reason: 'process/spawn',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'method',
    container: 'ClientRequest',
    wire: 'process/spawn',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L1333',
    cfgTestFixture: false,
  },
  {
    reason: 'process/writeStdin',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'method',
    container: 'ClientRequest',
    wire: 'process/writeStdin',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L1340',
    cfgTestFixture: false,
  },
  {
    reason: 'process/kill',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'method',
    container: 'ClientRequest',
    wire: 'process/kill',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L1347',
    cfgTestFixture: false,
  },
  {
    reason: 'process/resizePty',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'method',
    container: 'ClientRequest',
    wire: 'process/resizePty',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L1354',
    cfgTestFixture: false,
  },
  {
    reason: 'fuzzyFileSearch/sessionStart',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'method',
    container: 'ClientRequest',
    wire: 'fuzzyFileSearch/sessionStart',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L1436',
    cfgTestFixture: false,
  },
  {
    reason: 'fuzzyFileSearch/sessionUpdate',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'method',
    container: 'ClientRequest',
    wire: 'fuzzyFileSearch/sessionUpdate',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L1442',
    cfgTestFixture: false,
  },
  {
    reason: 'fuzzyFileSearch/sessionStop',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'method',
    container: 'ClientRequest',
    wire: 'fuzzyFileSearch/sessionStop',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L1448',
    cfgTestFixture: false,
  },
  {
    reason: 'currentTime/read',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'method',
    container: 'ServerRequest',
    wire: 'currentTime/read',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L1775',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/queue/changed',
    category: 'EXPERIMENTAL_REPRESENTABLE_ON_GENERATED_WIRE',
    kind: 'method',
    container: 'ServerNotification',
    wire: 'thread/queue/changed',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L1893',
    cfgTestFixture: false,
  },
  {
    reason: 'project/changed',
    category: 'EXPERIMENTAL_REPRESENTABLE_ON_GENERATED_WIRE',
    kind: 'method',
    container: 'ServerNotification',
    wire: 'project/changed',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L1895',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/project/updated',
    category: 'EXPERIMENTAL_REPRESENTABLE_ON_GENERATED_WIRE',
    kind: 'method',
    container: 'ServerNotification',
    wire: 'thread/project/updated',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L1897',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/environment/connected',
    category: 'EXPERIMENTAL_REPRESENTABLE_ON_GENERATED_WIRE',
    kind: 'method',
    container: 'ServerNotification',
    wire: 'thread/environment/connected',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L1899',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/environment/disconnected',
    category: 'EXPERIMENTAL_REPRESENTABLE_ON_GENERATED_WIRE',
    kind: 'method',
    container: 'ServerNotification',
    wire: 'thread/environment/disconnected',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L1901',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/settings/updated',
    category: 'EXPERIMENTAL_REPRESENTABLE_ON_GENERATED_WIRE',
    kind: 'method',
    container: 'ServerNotification',
    wire: 'thread/settings/updated',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L1903',
    cfgTestFixture: false,
  },
  {
    reason: 'autoApprovalReview/strictReviewRequired',
    category: 'EXPERIMENTAL_REPRESENTABLE_ON_GENERATED_WIRE',
    kind: 'method',
    container: 'ServerNotification',
    wire: 'autoApprovalReview/strictReviewRequired',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L1915',
    cfgTestFixture: false,
  },
  {
    reason: 'process/outputDelta',
    category: 'EXPERIMENTAL_REPRESENTABLE_ON_GENERATED_WIRE',
    kind: 'method',
    container: 'ServerNotification',
    wire: 'process/outputDelta',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L1928',
    cfgTestFixture: false,
  },
  {
    reason: 'process/exited',
    category: 'EXPERIMENTAL_REPRESENTABLE_ON_GENERATED_WIRE',
    kind: 'method',
    container: 'ServerNotification',
    wire: 'process/exited',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L1931',
    cfgTestFixture: false,
  },
  {
    reason: 'mcpServer/event/stream/notification',
    category: 'EXPERIMENTAL_REPRESENTABLE_ON_GENERATED_WIRE',
    kind: 'method',
    container: 'ServerNotification',
    wire: 'mcpServer/event/stream/notification',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L1942',
    cfgTestFixture: false,
  },
  {
    reason: 'turn/moderationMetadata',
    category: 'EXPERIMENTAL_REPRESENTABLE_ON_GENERATED_WIRE',
    kind: 'method',
    container: 'ServerNotification',
    wire: 'turn/moderationMetadata',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L1960',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/realtime/started',
    category: 'EXPERIMENTAL_REPRESENTABLE_ON_GENERATED_WIRE',
    kind: 'method',
    container: 'ServerNotification',
    wire: 'thread/realtime/started',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L1969',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/realtime/itemAdded',
    category: 'EXPERIMENTAL_REPRESENTABLE_ON_GENERATED_WIRE',
    kind: 'method',
    container: 'ServerNotification',
    wire: 'thread/realtime/itemAdded',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L1971',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/realtime/item/started',
    category: 'EXPERIMENTAL_REPRESENTABLE_ON_GENERATED_WIRE',
    kind: 'method',
    container: 'ServerNotification',
    wire: 'thread/realtime/item/started',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L1973',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/realtime/item/transcript/delta',
    category: 'EXPERIMENTAL_REPRESENTABLE_ON_GENERATED_WIRE',
    kind: 'method',
    container: 'ServerNotification',
    wire: 'thread/realtime/item/transcript/delta',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L1975',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/realtime/item/completed',
    category: 'EXPERIMENTAL_REPRESENTABLE_ON_GENERATED_WIRE',
    kind: 'method',
    container: 'ServerNotification',
    wire: 'thread/realtime/item/completed',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L1977',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/realtime/transcript/delta',
    category: 'EXPERIMENTAL_REPRESENTABLE_ON_GENERATED_WIRE',
    kind: 'method',
    container: 'ServerNotification',
    wire: 'thread/realtime/transcript/delta',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L1979',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/realtime/transcript/done',
    category: 'EXPERIMENTAL_REPRESENTABLE_ON_GENERATED_WIRE',
    kind: 'method',
    container: 'ServerNotification',
    wire: 'thread/realtime/transcript/done',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L1981',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/realtime/outputAudio/delta',
    category: 'EXPERIMENTAL_REPRESENTABLE_ON_GENERATED_WIRE',
    kind: 'method',
    container: 'ServerNotification',
    wire: 'thread/realtime/outputAudio/delta',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L1983',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/realtime/sdp',
    category: 'EXPERIMENTAL_REPRESENTABLE_ON_GENERATED_WIRE',
    kind: 'method',
    container: 'ServerNotification',
    wire: 'thread/realtime/sdp',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L1985',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/realtime/error',
    category: 'EXPERIMENTAL_REPRESENTABLE_ON_GENERATED_WIRE',
    kind: 'method',
    container: 'ServerNotification',
    wire: 'thread/realtime/error',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L1987',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/realtime/closed',
    category: 'EXPERIMENTAL_REPRESENTABLE_ON_GENERATED_WIRE',
    kind: 'method',
    container: 'ServerNotification',
    wire: 'thread/realtime/closed',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/common.rs#L1989',
    cfgTestFixture: false,
  },
  {
    reason: 'account/login/start.chatgptAuthTokens',
    category: 'EXPERIMENTAL_REPRESENTABLE_ON_GENERATED_WIRE',
    kind: 'variant',
    container: 'LoginAccountParams',
    wire: 'chatgptAuthTokens',
    tag: 'type',
    requestMethods: ['account/login/start'],
    positions: [{ method: 'account/login/start', field: null }],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/account.rs#L88',
    cfgTestFixture: false,
  },
  {
    reason: 'account/login/start.amazonBedrock',
    category: 'EXPERIMENTAL_REPRESENTABLE_ON_GENERATED_WIRE',
    kind: 'variant',
    container: 'LoginAccountParams',
    wire: 'amazonBedrock',
    tag: 'type',
    requestMethods: ['account/login/start'],
    positions: [{ method: 'account/login/start', field: null }],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/account.rs#L105',
    cfgTestFixture: false,
  },
  {
    reason: 'account/login/start.amazonBedrockAccessKeys',
    category: 'EXPERIMENTAL_REPRESENTABLE_ON_GENERATED_WIRE',
    kind: 'variant',
    container: 'LoginAccountParams',
    wire: 'amazonBedrockAccessKeys',
    tag: 'type',
    requestMethods: ['account/login/start'],
    positions: [{ method: 'account/login/start', field: null }],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/account.rs#L110',
    cfgTestFixture: false,
  },
  {
    reason: 'command/exec.permissionProfile',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'CommandExecParams',
    wire: 'permissionProfile',
    tag: null,
    requestMethods: ['command/exec'],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/command_exec.rs#L106',
    cfgTestFixture: false,
  },
  {
    reason: 'config/read.approvalsReviewer',
    category: 'EXPERIMENTAL_REPRESENTABLE_ON_GENERATED_WIRE',
    kind: 'field',
    container: 'Config',
    wire: 'approvals_reviewer',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/config.rs#L289',
    cfgTestFixture: false,
  },
  {
    reason: 'config/read.apps',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'Config',
    wire: 'apps',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/config.rs#L305',
    cfgTestFixture: false,
  },
  {
    reason: 'configRequirements/read.allowedApprovalsReviewers',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'ConfigRequirements',
    wire: 'allowedApprovalsReviewers',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/config.rs#L416',
    cfgTestFixture: false,
  },
  {
    reason: 'configRequirements/read.hooks',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'ConfigRequirements',
    wire: 'hooks',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/config.rs#L431',
    cfgTestFixture: false,
  },
  {
    reason: 'configRequirements/read.network',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'ConfigRequirements',
    wire: 'network',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/config.rs#L434',
    cfgTestFixture: false,
  },
  {
    reason: 'configRequirements/read.application',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'ConfigRequirements',
    wire: 'application',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/config.rs#L436',
    cfgTestFixture: false,
  },
  {
    reason: 'item/commandExecution/requestApproval.additionalPermissions',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'CommandExecutionRequestApprovalParams',
    wire: 'additionalPermissions',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/item.rs#L1578',
    cfgTestFixture: false,
  },
  {
    reason: 'item/commandExecution/requestApproval.availableDecisions',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'CommandExecutionRequestApprovalParams',
    wire: 'availableDecisions',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/item.rs#L1591',
    cfgTestFixture: false,
  },
  {
    reason: 'mcpServer/elicitation/request.userVerification',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'variant',
    container: 'McpServerElicitationRequest',
    wire: 'openai/userVerification',
    tag: 'mode',
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/mcp.rs#L755',
    cfgTestFixture: false,
  },
  {
    reason: 'askForApproval.granular',
    category: 'EXPERIMENTAL_REPRESENTABLE_ON_GENERATED_WIRE',
    kind: 'variant',
    container: 'AskForApproval',
    wire: 'granular',
    tag: null,
    requestMethods: [],
    positions: [{ method: 'thread/fork', field: 'approvalPolicy' }, { method: 'thread/resume', field: 'approvalPolicy' }, { method: 'thread/start', field: 'approvalPolicy' }, { method: 'turn/start', field: 'approvalPolicy' }],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/shared.rs#L181',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/start.allowProviderModelFallback',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'ThreadStartParams',
    wire: 'allowProviderModelFallback',
    tag: null,
    requestMethods: ['thread/start'],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/thread.rs#L69',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/start.runtimeWorkspaceRoots',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'ThreadStartParams',
    wire: 'runtimeWorkspaceRoots',
    tag: null,
    requestMethods: ['thread/start'],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/thread.rs#L83',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/start.permissions',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'ThreadStartParams',
    wire: 'permissions',
    tag: null,
    requestMethods: ['thread/start'],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/thread.rs#L96',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/start.multiAgentMode',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'ThreadStartParams',
    wire: 'multiAgentMode',
    tag: null,
    requestMethods: ['thread/start'],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/thread.rs#L110',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/start.historyMode',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'ThreadStartParams',
    wire: 'historyMode',
    tag: null,
    requestMethods: ['thread/start'],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/thread.rs#L116',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/start.projectId',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'ThreadStartParams',
    wire: 'projectId',
    tag: null,
    requestMethods: ['thread/start'],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/thread.rs#L126',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/start.environments',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'ThreadStartParams',
    wire: 'environments',
    tag: null,
    requestMethods: ['thread/start'],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/thread.rs#L135',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/start.dynamicTools',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'ThreadStartParams',
    wire: 'dynamicTools',
    tag: null,
    requestMethods: ['thread/start'],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/thread.rs#L138',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/start.selectedCapabilityRoots',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'ThreadStartParams',
    wire: 'selectedCapabilityRoots',
    tag: null,
    requestMethods: ['thread/start'],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/thread.rs#L146',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/start.mockExperimentalField',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'ThreadStartParams',
    wire: 'mockExperimentalField',
    tag: null,
    requestMethods: ['thread/start'],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/thread.rs#L151',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/start.experimentalRawEvents',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'ThreadStartParams',
    wire: 'experimentalRawEvents',
    tag: null,
    requestMethods: ['thread/start'],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/thread.rs#L156',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/start.runtimeWorkspaceRoots',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'ThreadStartResponse',
    wire: 'runtimeWorkspaceRoots',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/thread.rs#L189',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/start.activePermissionProfile',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'ThreadStartResponse',
    wire: 'activePermissionProfile',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/thread.rs#L204',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/start.multiAgentMode',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'ThreadStartResponse',
    wire: 'multiAgentMode',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/thread.rs#L209',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/settings/update.permissions',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'ThreadSettingsUpdateParams',
    wire: 'permissions',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/thread.rs#L243',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/settings/update.collaborationMode',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'ThreadSettingsUpdateParams',
    wire: 'collaborationMode',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/thread.rs#L269',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/settings/update.multiAgentMode',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'ThreadSettingsUpdateParams',
    wire: 'multiAgentMode',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/thread.rs#L273',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/settings.multiAgentMode',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'ThreadSettings',
    wire: 'multiAgentMode',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/thread.rs#L302',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/resume.history',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'ThreadResumeParams',
    wire: 'history',
    tag: null,
    requestMethods: ['thread/resume'],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/thread.rs#L341',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/resume.path',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'ThreadResumeParams',
    wire: 'path',
    tag: null,
    requestMethods: ['thread/resume'],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/thread.rs#L349',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/resume.runtimeWorkspaceRoots',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'ThreadResumeParams',
    wire: 'runtimeWorkspaceRoots',
    tag: null,
    requestMethods: ['thread/resume'],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/thread.rs#L373',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/resume.permissions',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'ThreadResumeParams',
    wire: 'permissions',
    tag: null,
    requestMethods: ['thread/resume'],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/thread.rs#L387',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/resume.initialTurnsPage',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'ThreadResumeParams',
    wire: 'initialTurnsPage',
    tag: null,
    requestMethods: ['thread/resume'],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/thread.rs#L407',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/resume.runtimeWorkspaceRoots',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'ThreadResumeResponse',
    wire: 'runtimeWorkspaceRoots',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/thread.rs#L423',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/resume.activePermissionProfile',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'ThreadResumeResponse',
    wire: 'activePermissionProfile',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/thread.rs#L438',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/resume.multiAgentMode',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'ThreadResumeResponse',
    wire: 'multiAgentMode',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/thread.rs#L443',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/resume.initialTurnsPage',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'ThreadResumeResponse',
    wire: 'initialTurnsPage',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/thread.rs#L447',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/fork.beforeTurnId',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'ThreadForkParams',
    wire: 'beforeTurnId',
    tag: null,
    requestMethods: ['thread/fork'],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/thread.rs#L530',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/fork.path',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'ThreadForkParams',
    wire: 'path',
    tag: null,
    requestMethods: ['thread/fork'],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/thread.rs#L536',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/fork.runtimeWorkspaceRoots',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'ThreadForkParams',
    wire: 'runtimeWorkspaceRoots',
    tag: null,
    requestMethods: ['thread/fork'],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/thread.rs#L560',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/fork.permissions',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'ThreadForkParams',
    wire: 'permissions',
    tag: null,
    requestMethods: ['thread/fork'],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/thread.rs#L574',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/fork.deferGoalContinuation',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'ThreadForkParams',
    wire: 'deferGoalContinuation',
    tag: null,
    requestMethods: ['thread/fork'],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/thread.rs#L598',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/fork.runtimeWorkspaceRoots',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'ThreadForkResponse',
    wire: 'runtimeWorkspaceRoots',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/thread.rs#L614',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/fork.activePermissionProfile',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'ThreadForkResponse',
    wire: 'activePermissionProfile',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/thread.rs#L629',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/fork.multiAgentMode',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'ThreadForkResponse',
    wire: 'multiAgentMode',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/thread.rs#L634',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/metadata/update.projectId',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'ThreadMetadataUpdateParams',
    wire: 'projectId',
    tag: null,
    requestMethods: ['thread/metadata/update'],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/thread.rs#L983',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/metadata/update.daybreakEnabled',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'ThreadMetadataUpdateParams',
    wire: 'daybreakEnabled',
    tag: null,
    requestMethods: ['thread/metadata/update'],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/thread.rs#L994',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/list.projectId',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'ThreadListParams',
    wire: 'projectId',
    tag: null,
    requestMethods: ['thread/list'],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/thread.rs#L1416',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/list.parentThreadId',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'ThreadListParams',
    wire: 'parentThreadId',
    tag: null,
    requestMethods: ['thread/list'],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/thread.rs#L1438',
    cfgTestFixture: false,
  },
  {
    reason: 'thread/list.ancestorThreadId',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'ThreadListParams',
    wire: 'ancestorThreadId',
    tag: null,
    requestMethods: ['thread/list'],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/thread.rs#L1443',
    cfgTestFixture: false,
  },
  {
    reason: 'thread.environments',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'Thread',
    wire: 'environments',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/thread_data.rs#L210',
    cfgTestFixture: false,
  },
  {
    reason: 'thread.extra',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'Thread',
    wire: 'extra',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/thread_data.rs#L214',
    cfgTestFixture: false,
  },
  {
    reason: 'thread.canAcceptDirectInput',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'Thread',
    wire: 'canAcceptDirectInput',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/thread_data.rs#L274',
    cfgTestFixture: false,
  },
  {
    reason: 'thread.daybreakEnabled',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'Thread',
    wire: 'daybreakEnabled',
    tag: null,
    requestMethods: [],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/thread_data.rs#L287',
    cfgTestFixture: false,
  },
  {
    reason: 'turn/start.responsesapiClientMetadata',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'TurnStartParams',
    wire: 'responsesapiClientMetadata',
    tag: null,
    requestMethods: ['turn/start'],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/turn.rs#L174',
    cfgTestFixture: false,
  },
  {
    reason: 'turn/start.additionalContext',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'TurnStartParams',
    wire: 'additionalContext',
    tag: null,
    requestMethods: ['turn/start'],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/turn.rs#L178',
    cfgTestFixture: false,
  },
  {
    reason: 'turn/start.environments',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'TurnStartParams',
    wire: 'environments',
    tag: null,
    requestMethods: ['turn/start'],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/turn.rs#L186',
    cfgTestFixture: false,
  },
  {
    reason: 'turn/start.runtimeWorkspaceRoots',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'TurnStartParams',
    wire: 'runtimeWorkspaceRoots',
    tag: null,
    requestMethods: ['turn/start'],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/turn.rs#L194',
    cfgTestFixture: false,
  },
  {
    reason: 'turn/start.permissions',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'TurnStartParams',
    wire: 'permissions',
    tag: null,
    requestMethods: ['turn/start'],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/turn.rs#L210',
    cfgTestFixture: false,
  },
  {
    reason: 'turn/start.collaborationMode',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'TurnStartParams',
    wire: 'collaborationMode',
    tag: null,
    requestMethods: ['turn/start'],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/turn.rs#L249',
    cfgTestFixture: false,
  },
  {
    reason: 'turn/start.multiAgentMode',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'TurnStartParams',
    wire: 'multiAgentMode',
    tag: null,
    requestMethods: ['turn/start'],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/turn.rs#L254',
    cfgTestFixture: false,
  },
  {
    reason: 'turn/start.cyberAccessProgram',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'TurnStartParams',
    wire: 'cyberAccessProgram',
    tag: null,
    requestMethods: ['turn/start'],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/turn.rs#L260',
    cfgTestFixture: false,
  },
  {
    reason: 'turn/steer.responsesapiClientMetadata',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'TurnSteerParams',
    wire: 'responsesapiClientMetadata',
    tag: null,
    requestMethods: ['turn/steer'],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/turn.rs#L289',
    cfgTestFixture: false,
  },
  {
    reason: 'turn/steer.additionalContext',
    category: 'EXPERIMENTAL_ABSENT_FROM_GENERATED_WIRE',
    kind: 'field',
    container: 'TurnSteerParams',
    wire: 'additionalContext',
    tag: null,
    requestMethods: ['turn/steer'],
    positions: [],
    anchor: 'codex-rs/app-server-protocol/src/protocol/v2/turn.rs#L293',
    cfgTestFixture: false,
  },
]);
