// Sensitive Data OS — provenance / source-quality vocabulary (PR-SD1).
//
// SD1 introduces the typed surface so future SD/connector slices can normalize
// where a sensitive-data finding came from and how trustworthy that signal is,
// WITHOUT implementing connector ingestion in this PR. The deterministic
// precedence helper below is pure TypeScript; it encodes one safety rule:
// native GovAI evidence cannot be downgraded by external/connector signals,
// even when the external signal is structurally stricter on action.
//
// `connector_*` and `external_*` source surfaces are accepted as types here
// purely so future code can describe ingested findings using the same
// vocabulary; SD1 does NOT itself ingest from any connector.

export const SENSITIVE_DATA_ORIGINS = [
  'govai_native',
  'connector_ingested',
  'customer_supplied',
  'external_import',
] as const;
export type SensitiveDataOrigin = (typeof SENSITIVE_DATA_ORIGINS)[number];

export const SENSITIVE_DATA_SOURCE_SURFACES = [
  // GovAI-native scan surfaces.
  'openai_native',
  'anthropic_native',
  'govai_runs',
  // Connector-ingested surfaces (placeholders; not implemented in SD1).
  'connector_microsoft',
  'connector_aws',
  'connector_google',
  'connector_nvidia_nim',
  'connector_nemo_guardrails',
  'connector_openclaw',
  'connector_other_agent_runtime',
  'connector_other',
  // External / customer surfaces.
  'manual_upload',
  'api_import',
] as const;
export type SensitiveDataSourceSurface = (typeof SENSITIVE_DATA_SOURCE_SURFACES)[number];

/**
 * Quality ranking of the underlying evidence chain. Higher quality = more
 * trustworthy and harder to override.
 *
 * Order (most → least trustworthy):
 *   1. `primary_govai_evidence`    — produced by a GovAI native detector with
 *                                     full audit chain anchoring.
 *   2. `provider_generated`        — produced by an upstream model/provider
 *                                     surface (OpenAI / Anthropic native flags),
 *                                     observed via GovAI but not generated by it.
 *   3. `customer_attested`         — labeled by the tenant customer with a
 *                                     known identity (e.g., an admin tag).
 *   4. `normalized_external`       — ingested from an external system and
 *                                     re-typed into the SD1 vocabulary.
 *   5. `unverified_external`       — ingested without a trust anchor.
 */
export const SENSITIVE_DATA_SOURCE_QUALITIES = [
  'primary_govai_evidence',
  'provider_generated',
  'customer_attested',
  'normalized_external',
  'unverified_external',
] as const;
export type SensitiveDataSourceQuality =
  (typeof SENSITIVE_DATA_SOURCE_QUALITIES)[number];

const QUALITY_RANK: Record<SensitiveDataSourceQuality, number> = {
  primary_govai_evidence: 4,
  provider_generated: 3,
  customer_attested: 2,
  normalized_external: 1,
  unverified_external: 0,
};

/**
 * Compare two source-quality tokens.
 *
 * Returns:
 *  -  1 when `a` outranks `b` (a is stricter / more trustworthy);
 *  - -1 when `b` outranks `a`;
 *  -  0 on equal rank.
 */
export function compareSourceQuality(
  a: SensitiveDataSourceQuality,
  b: SensitiveDataSourceQuality,
): -1 | 0 | 1 {
  const ra = QUALITY_RANK[a];
  const rb = QUALITY_RANK[b];
  if (ra > rb) return 1;
  if (ra < rb) return -1;
  return 0;
}

export function isNativeQuality(q: SensitiveDataSourceQuality): boolean {
  // SD1 treats primary GovAI evidence as the only native quality. Everything
  // else — including provider-generated flags — is enrichment that can be
  // escalated against but cannot downgrade a native finding.
  return q === 'primary_govai_evidence';
}

/**
 * Deterministic merge rule for two findings reporting on the same subject.
 * Encodes the SD1 safety invariants:
 *
 *  - Native GovAI evidence (`primary_govai_evidence`) cannot be downgraded by
 *    connector/external evidence, ever — even when the external evidence
 *    arrives with a structurally stricter recommended action.
 *  - Connector/external evidence MAY escalate a native finding if it is
 *    stricter AND the native finding is not itself native-primary.
 *  - When both are native-primary, the stricter one wins.
 *  - Tie-breaks resolve conservatively: keep the finding with the higher
 *    quality; if quality ties, keep the stricter recommended action; if those
 *    tie too, return `a` to keep the call site deterministic.
 *
 * This is pure: callers pass two opaque records and a `stricter` decider.
 */
export type FindingForMerge<T> = {
  value: T;
  source_quality: SensitiveDataSourceQuality;
  /**
   * Strictness rank of this finding's recommended action. Higher = stricter.
   * The caller maps `recommended_action` → number (see
   * `recommendedActionRank` in `sensitive-findings.ts`).
   */
  action_rank: number;
};

export function mergeBySourcePrecedence<T>(
  a: FindingForMerge<T>,
  b: FindingForMerge<T>,
): FindingForMerge<T> {
  const aNative = isNativeQuality(a.source_quality);
  const bNative = isNativeQuality(b.source_quality);

  // Rule 1: native primary cannot be downgraded by non-native.
  if (aNative && !bNative) return a;
  if (bNative && !aNative) return b;

  // Rule 2 & 3: same native-ness — quality wins, then strictness.
  const qcmp = compareSourceQuality(a.source_quality, b.source_quality);
  if (qcmp > 0) return a;
  if (qcmp < 0) return b;

  // Quality tie: stricter action wins.
  if (a.action_rank > b.action_rank) return a;
  if (b.action_rank > a.action_rank) return b;

  // Full tie: keep `a` for determinism.
  return a;
}
