// Sensitive Data OS — provenance / source-quality vocabulary (PR-SD1).
//
// SD1 introduces the typed surface so future SD/connector slices can normalize
// where a sensitive-data finding came from and how trustworthy that signal is,
// WITHOUT implementing connector ingestion in this PR. The deterministic
// precedence helper below is pure TypeScript; it encodes one safety rule:
// native GovAI evidence cannot be downgraded by external/connector signals,
// even when the external signal is structurally stricter on action.
//
// `connector_*` and `external_*` source surfaces are accepted as types here
// purely so future code can describe ingested findings using the same
// vocabulary; SD1 does NOT itself ingest from any connector.

export const SENSITIVE_DATA_ORIGINS = [
  'govai_native',
  'connector_ingested',
  'customer_supplied',
  'external_import',
] as const;
export type SensitiveDataOrigin = (typeof SENSITIVE_DATA_ORIGINS)[number];

export const SENSITIVE_DATA_SOURCE_SURFACES = [
  // GovAI-native scan surfaces.
  'openai_native',
  'anthropic_native',
  'govai_runs',
  // Connector-ingested surfaces (placeholders; not implemented in SD1).
  'connector_microsoft',
  'connector_aws',
  'connector_google',
  'connector_nvidia_nim',
  'connector_nemo_guardrails',
  'connector_openclaw',
  'connector_other_agent_runtime',
  'connector_other',
  // External / customer surfaces.
  'manual_upload',
  'api_import',
] as const;
export type SensitiveDataSourceSurface = (typeof SENSITIVE_DATA_SOURCE_SURFACES)[number];

/**
 * Quality ranking of the underlying evidence chain. Higher quality = more
 * trustworthy and harder to override.
 *
 * Order (most → least trustworthy):
 *   1. `primary_govai_evidence`    — produced by a GovAI native detector with
 *                                     full audit chain anchoring.
 *   2. `provider_generated`        — produced by an upstream model/provider
 *                                     surface (OpenAI / Anthropic native flags),
 *                                     observed via GovAI but not generated by it.
 *   3. `customer_attested`         — labeled by the tenant customer with a
 *                                     known identity (e.g., an admin tag).
 *   4. `normalized_external`       — ingested from an external system and
 *                                     re-typed into the SD1 vocabulary.
 *   5. `unverified_external`       — ingested without a trust anchor.
 */
export const SENSITIVE_DATA_SOURCE_QUALITIES = [
  'primary_govai_evidence',
  'provider_generated',
  'customer_attested',
  'normalized_external',
  'unverified_external',
] as const;
export type SensitiveDataSourceQuality =
  (typeof SENSITIVE_DATA_SOURCE_QUALITIES)[number];

const QUALITY_RANK: Record<SensitiveDataSourceQuality, number> = {
  primary_govai_evidence: 4,
  provider_generated: 3,
  customer_attested: 2,
  normalized_external: 1,
  unverified_external: 0,
};

/**
 * Compare two source-quality tokens.
 *
 * Returns:
 *  -  1 when `a` outranks `b` (a is stricter / more trustworthy);
 *  - -1 when `b` outranks `a`;
 *  -  0 on equal rank.
 */
export function compareSourceQuality(
  a: SensitiveDataSourceQuality,
  b: SensitiveDataSourceQuality,
): -1 | 0 | 1 {
  const ra = QUALITY_RANK[a];
  const rb = QUALITY_RANK[b];
  if (ra > rb) return 1;
  if (ra < rb) return -1;
  return 0;
}

export function isNativeQuality(q: SensitiveDataSourceQuality): boolean {
  // SD1 treats primary GovAI evidence as the only native quality. Everything
  // else — including provider-generated flags — is enrichment that can be
  // escalated against but cannot downgrade a native finding.
  return q === 'primary_govai_evidence';
}

/**
 * Opaque record describing one finding for the deterministic precedence
 * helpers below. Callers wrap their domain object (`value`) with the source
 * quality and a numeric strictness rank (see `recommendedActionRank` in
 * `sensitive-findings.ts`); the helpers stay pure and reusable.
 */
export type FindingForMerge<T> = {
  value: T;
  source_quality: SensitiveDataSourceQuality;
  /**
   * Strictness rank of this finding's recommended action. Higher = stricter.
   * The caller maps `recommended_action` → number (see
   * `recommendedActionRank` in `sensitive-findings.ts`).
   */
  action_rank: number;
};

/**
 * Reason code explaining how `decideSourcePrecedence` reached its result.
 * Useful for audit trails and tests that need to assert the rule that fired,
 * not just the selected value.
 */
export type SourcePrecedenceReason =
  | 'native_primary_selected'
  | 'external_escalation_preserved'
  | 'higher_quality_selected'
  | 'stricter_action_selected'
  | 'deterministic_tie';

/**
 * Result of comparing two findings under SD1 precedence rules. `selected` is
 * the authoritative finding; `escalation` (optional) is the OTHER finding when
 * it carries a stricter signal worth preserving as metadata — typically the
 * case when external/connector evidence is stricter than a native-primary
 * finding it cannot downgrade. `reason` records which rule fired.
 *
 * SD1 contract: `escalation` is metadata only. It does NOT alter
 * `DlpScanResult.highestAction`, does NOT influence `decidePolicy`, and does
 * NOT trigger runtime blocking. Later SD/RT slices may consume it to route
 * findings for qualified-counsel / DPO / security review.
 */
export type SourcePrecedenceDecision<T> = {
  selected: FindingForMerge<T>;
  escalation?: FindingForMerge<T>;
  reason: SourcePrecedenceReason;
};

/**
 * Decide precedence between two findings reporting on the same subject.
 * Encodes the SD1 safety invariants from the regulatory operating model:
 *
 *  - Native GovAI evidence (`primary_govai_evidence`) cannot be downgraded by
 *    connector/external evidence, ever — even when the external evidence
 *    arrives with a structurally stricter recommended action.
 *  - Connector/external evidence MAY be preserved as `escalation` metadata
 *    when it carries a stricter action than the native-primary finding it
 *    accompanies. The native finding stays `selected`; the external signal is
 *    surfaced as `escalation` so callers do not silently discard a stricter
 *    review signal.
 *  - Unverified external evidence can become an escalation signal, but it
 *    never overrides primary GovAI evidence — provenance stays explicit.
 *  - When both findings are native-primary, the stricter action wins.
 *  - When neither is native-primary, higher quality wins; on quality tie the
 *    stricter action wins; on a full tie `a` is returned for determinism.
 *
 * This is a pure function over opaque records — no IO, no enforcement.
 */
export function decideSourcePrecedence<T>(
  a: FindingForMerge<T>,
  b: FindingForMerge<T>,
): SourcePrecedenceDecision<T> {
  const aNative = isNativeQuality(a.source_quality);
  const bNative = isNativeQuality(b.source_quality);

  // Mixed native vs non-native: the native finding is authoritative, but a
  // stricter non-native signal is preserved as escalation metadata.
  if (aNative && !bNative) {
    if (b.action_rank > a.action_rank) {
      return { selected: a, escalation: b, reason: 'external_escalation_preserved' };
    }
    return { selected: a, reason: 'native_primary_selected' };
  }
  if (bNative && !aNative) {
    if (a.action_rank > b.action_rank) {
      return { selected: b, escalation: a, reason: 'external_escalation_preserved' };
    }
    return { selected: b, reason: 'native_primary_selected' };
  }

  // Both native-primary or both non-native: quality wins, then strictness.
  const qcmp = compareSourceQuality(a.source_quality, b.source_quality);
  if (qcmp > 0) return { selected: a, reason: 'higher_quality_selected' };
  if (qcmp < 0) return { selected: b, reason: 'higher_quality_selected' };

  // Quality tie: stricter action wins.
  if (a.action_rank > b.action_rank) {
    return { selected: a, reason: 'stricter_action_selected' };
  }
  if (b.action_rank > a.action_rank) {
    return { selected: b, reason: 'stricter_action_selected' };
  }

  // Full tie: keep `a` for determinism.
  return { selected: a, reason: 'deterministic_tie' };
}

/**
 * Selected-only convenience wrapper over `decideSourcePrecedence`. Returns the
 * authoritative finding without the escalation metadata. Callers that need to
 * preserve external escalation signals should use `decideSourcePrecedence`
 * directly so the stricter external signal is not silently discarded.
 *
 * This wrapper exists for backward compatibility and for call sites where a
 * single representative finding is the right contract.
 */
export function mergeBySourcePrecedence<T>(
  a: FindingForMerge<T>,
  b: FindingForMerge<T>,
): FindingForMerge<T> {
  return decideSourcePrecedence(a, b).selected;
}
